### ISSUE TITLE
timeout on connnection

### ISSUE THREAD

**Issue by netbitsolutions** [sekando/feednami-client#1]
Hi, thanks for this script. I have a request.  We need a  connection timeout parameter to be configured. I.e if feeds can't be retreived after x seconds, perform another action like a notification: 'No connection at the moment'

**Comment by richardkazuomiller** [comment]
Thanks for the request! That's a good idea; currently the client doesn't handle poor internet connections well and fails silently. I won't be able to work on this for a few days but I'd be willing to accept a PR if you're up for it.

Something like:

````
feednami.load({
  url: 'http://foobar.com/hoge.rss',
  timeout: 5000
},function(res){
 if(res.error && res.error.timedOut){
    console.log(res.error.message) //"No connection at the moment"
 }
})
````

is what you're thinking of right?

If you need a timeout immediately you could implement it like this for now:
````
var finished = false;
setTimeout(function(){
  if(!finished){
    finished = true;
    alert('No connection at the moment')
  }
},5000);
feednami.load(url,function(res){
  if(!finished){
    finished = true;
    //do something
  }
})
````

**Comment by netbitsolutions** [comment]
Thanks alot, i will use your suggestion

**Comment by netbitsolutions** [comment]
Hi, thanks again

How do i implement this code

var finished = false;
setTimeout(function(){
  if(!finished){
    finished = true;
    alert('No connection at the moment')
  }
},5000);
feednami.load(url,function(res){
  if(!finished){
    finished = true;
    //do something
  }
})
