### ISSUE TITLE
server code source?

### ISSUE THREAD

**Issue by eudago** [sekando/feednami-client#2]
Hi, this is a client but the part of the server code is public?

I'm interested in knowing how it works

**Comment by richardkazuomiller** [comment]
Hi, I'm not planning on making the server source public but basically all it does is download the contents of the feed URL using [Request](https://github.com/request/request) and passes them into [Feedparser](https://github.com/danmactough/node-feedparser) and returns the result. For the Google Feed API compatibility stuff it just rearranges some of the properties.

If enough people want an open source version of the server side part, I'm open to that idea, but right now I want to focus on providing a simple solution for people that doesn't require managing servers.
